use std::fs::File;
use std::io::BufWriter;
use std::path::PathBuf;

use forgedthoughts::prelude::*;

fn main() {

    let ft = FT::new();

    let rc = ft.compile(PathBuf::new());

    if rc.is_ok() {
        if let Some(mut ctx) = rc.ok() {

            let mut buffer = ColorBuffer::new(ctx.settings.width as usize, ctx.settings.height as usize, 0.0);
            ft.render(&mut ctx, &mut buffer);

            let out = buffer.to_u8_vec();

            // Write it to file

            let path = "main.png";
            let file = File::create(path).unwrap();
            let ref mut w = BufWriter::new(file);

            let mut encoder = png::Encoder::new(w, ctx.settings.width as u32, ctx.settings.height as u32);
            encoder.set_color(png::ColorType::Rgba);
            encoder.set_depth(png::BitDepth::Eight);
            // Adding text chunks to the header
            encoder
                .add_text_chunk(
                    "ForgedThughts".to_string(),
                    "This image was generated by ForgedThoughs.".to_string(),
                )
                .unwrap();

            let mut writer = encoder.write_header().unwrap();

            writer.write_image_data(&out).unwrap(); // Save
        }
    }
}
